#!/bin/sh

# Load su/sling daemon
launchctl load /Library/LaunchDaemons/xyz.willy.supersling.plist

# Prevent Zebra from choosing a sandbox path for its directory
if [ -f /var/mobile/Containers/Data/Application/*/Documents/zebra.db ];then
    DBPATH=$(ls /var/mobile/Containers/Data/Application/*/Documents/zebra.db)
    ZBPATH=${DBPATH/Documents\/zebra.db/}
    rm -rf ${ZBPATH}
    echo "Removed sandboxed Zebra document directory"
fi

if [ -d "/var/mobile/Library/Application Support/xyz.willy.Zebra" ];then
    chown -R mobile:mobile "/var/mobile/Library/Application Support/xyz.willy.Zebra"
    chmod -R +r "/var/mobile/Library/Application Support/xyz.willy.Zebra"
fi