#!/bin/sh

# Unload supersling daemon
launchctl unload /Library/LaunchDaemons/xyz.willy.supersling.plist 2>&1 > /dev/null

# Move Zebra data from old documents directory
if [ -d /var/mobile/Documents/xyz.willy.Zebra ];then
    echo "Moving Zebra data from /var/mobile/Documents to /var/mobile/Library/Application Support"
    cp -R /var/mobile/Documents/xyz.willy.Zebra "/var/mobile/Library/Application Support/"
    rm -rf /var/mobile/Documents/xyz.willy.Zebra
fi